language: python
sudo: false
cache:
  - pip
python:
  - 3.6
env:
  global:
    - ASYNC_TEST_TIMEOUT=15
    - ETCDCTL_API=3

# installing dependencies
before_install:
  - pip install --upgrade setuptools pip
  - pip install --pre -r dev-requirements.txt --upgrade .
install:
  - python -m jupyterhub_traefik_proxy.install --output=./bin
  - export PATH=$PWD/bin:$PATH
  - pip freeze

# running tests
script:
  - pytest -v
after_success:
  - codecov

# auto-deploy releases on tags
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: jupyterhub-bot
  password:
    secure: mZbQVF80AO+cxJM/0qbeFoAcHSBE3YSeT4igUXlKypRVEc0qNskJbh6Ofh5qIHb4dO/LF7Si3Bms1cP3Wai7wPFAglGPV/CQ3TQjrwjWy1FYwyAvduSiKZ7xsHoSvVakqfzl8R/XSmBbajbECts+7NuJuyJGAvWldeHlWo7UXt+wiKFCK8jGcXcqCcf8F8kVkF7gfx+Z/sO3JMintMclz+N3GoUiNYnmZ3fI3PEoFeDETGy9mzlM8eQi6LnZ16rod53KKA1q3EKziNvqVgYObgD95NfH/gtgZ+rDhEIS0kPMUUu5ihfofvY/I2tV3IX/Pbih2ssHDRolthVcbPP1+L1WdCPos7IpEHKDYZuTwMizuaPaGes2YHREMCN3AtncT456X4gtH7KuWG3gAXOrmTLDp+ShaevoJCF0Qk2E0WzVngqV//stFOhwZaxV1uRb4xujTI0Ak35yKnfuiLbrOyoZ+8eiwOwhE2C0l3BKNy+xLpBMQZVoX87WTPrQzNOv6bV5ZX9Mp+pJTOnUFJOrwvLHCm3hZtWMcijAVNuR3Wi0zsJVaqCtB7/qqUtWw1PUpwyVnA9DpgGOxXo4+tVDy75izq0GTYivqpFq9EyXzE2UyxDjgRK+I3OAEUiSJ1tIGw/T2306iVf2EfpMVjWQdX4Wnz+b123bTIE7haoiUxc=
  on:
    tags: true
    repo: jupyterhub/traefik-proxy
