[build-system]
requires = ["setuptools", "versioneer", "wheel"]

[tool.black]
exclude = '''
/(
  .git
| build
| dist
| _version\.py
| versioneer\.py
| docs/source/conf.py
| docs/sphinxext/autodoc_traits.py
)
'''
